"""Compatibility facade for CLI argument parsing."""

from grafconflux._config.args_parser import ArgsParser
from grafconflux._config.yaml_settings import (
    DEFAULT_CONFLUENCE_UPLOAD_THREADS,
    DEFAULT_CONTINUE_ON_ERROR,
    DEFAULT_GRAPH_WIDTH,
    DEFAULT_IGNORE_VERIFY_SSL,
    DEFAULT_RETRY,
    DEFAULT_RETRY_BACKOFF_MULTIPLIER,
    DEFAULT_RETRY_COUNT,
    DEFAULT_RETRY_DELAY,
    DEFAULT_RETRY_JITTER,
    DEFAULT_RETRY_MAX_DELAY,
    DEFAULT_THREADS,
    DEFAULT_UPLOAD_DELAY,
    DEFAULT_UPLOAD_RATE_PER_SECOND,
    YAML_SETTING_NAMES,
    YamlSettings,
    ignore_verify_ssl_or_current,
    setting_or_current,
    verify_ssl_or_current,
    wiki_url_or_current,
    yaml_settings_from_config,
)
from grafconflux._shared.time import GrafanaTimeBase, GrafanaTimeDownloader, GrafanaTimeUploader

__all__ = [
    "ArgsParser",
    "DEFAULT_CONFLUENCE_UPLOAD_THREADS",
    "DEFAULT_CONTINUE_ON_ERROR",
    "DEFAULT_GRAPH_WIDTH",
    "DEFAULT_IGNORE_VERIFY_SSL",
    "DEFAULT_RETRY",
    "DEFAULT_RETRY_BACKOFF_MULTIPLIER",
    "DEFAULT_RETRY_COUNT",
    "DEFAULT_RETRY_DELAY",
    "DEFAULT_RETRY_JITTER",
    "DEFAULT_RETRY_MAX_DELAY",
    "DEFAULT_THREADS",
    "DEFAULT_UPLOAD_DELAY",
    "DEFAULT_UPLOAD_RATE_PER_SECOND",
    "GrafanaTimeBase",
    "GrafanaTimeDownloader",
    "GrafanaTimeUploader",
    "YAML_SETTING_NAMES",
    "YamlSettings",
    "ignore_verify_ssl_or_current",
    "setting_or_current",
    "verify_ssl_or_current",
    "wiki_url_or_current",
    "yaml_settings_from_config",
]
